version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ryh2-week8"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qzd5u5aoi8a6"
s3_prefix = "ryh2-week8"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
