AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ryhma2_week8

Globals:
  Function:
    Timeout: 3

Resources:
  GetStationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambdajoona.lambda_handler
      Runtime: python3.9
      Events:
        GetStation:
          Type: Api
          Properties:
            Path: /
            Method: get
  
  UpdateDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Events:
        ScanDB:
          Type: Api
          Properties:
            Path: /koodit
            Method: get

    Layers:
      - !Ref libs

    libs:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: requests-lib
        Content:
          S3Bucket: my-bucket-region-123456789012
          S3Key: layer.zip
      CompatibleRuntimes:
        - python3.9