AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ryhma2_week8

  

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetStationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: getdatabasestation.lambda_handler
      Runtime: python3.9
      Events:
        GetStation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /koodit
            Method: get
    Layers:
      - !reference libs

    libs:
      Type: AWS::Lambda::LayerVersion
      Properties:
        LayerName: requests-lib
        Content:
          S3Bucket: my-bucket-region-123456789012
          S3Key: layer.zip
      CompatibleRuntimes:
        - python3.9      


